### ISSUE TITLE
Getting it to work in Webpack

### ISSUE THREAD

**Issue by jaredcwhite** [Aaron-Bird/bamboo#1]
Hi Aaron, I've been using Bamboo on a project that will be going live soon, and it's been pretty great so far.

I recently switched from using Gulp to using Webpack for my frontend assets, and I had to make a few modifications to the bamboo js file to get it to work well with a Webpack import statement. I'm not sure if those modifications would be backwards compatible with a Gulp workflow. Anyway, if you'd like me to submit a PR to at least take a look, let me know. I'm not sure if the project is being actively maintained. Thanks -J

**Comment by Aaron-Bird** [comment]
Yes, you can submit a PR.
